
//=============================================================================
// connect to mongodb
//=============================================================================

const { MongoClient} = require("mongodb");

//generated by mongodb website
const uri  = "mongodb+srv://scurvy-mango:mango.scurvy@scurvy-mango.qpzfz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority";

//create a new mongo client
const client = new MongoClient(uri);

async function run(){
    try{

        //connect the client to the server
        await client.connect();

        //establish and verify connection
        await client.db("admin").command({ ping: 1});
        console.log("Connected successfully to server");
    } finally {
        //ensures that the client will close when you finish/error
        await client.close();
    }
}

run().catch(console.dir);

//=============================================================================
// print data from mongodb
//=============================================================================

client.connection.db.collection('sample_geospatial',function(err,docs){
    //check for errors
    if(err) return console.log(err);
    //walk thruogh the cursor
    docs.find().each(function(err,doc){
        //check for errors again
        if(err) return console.err(err);
        //log document
        console.log(doc);
    })
});
